/** 項目の絵文字ピッカー一覧（カウンター・フローチャート共通） */
export const EMOJI_OPTIONS = [
    "📊",
    "🗾",
    "➖",
    "♈",
    "♉",
    "♊",
    "♋",
    "♌",
    "♍",
    "♎",
    "♏",
    "♐",
    "♑",
    "♒",
    "♓",
    "🅰️",
    "🅱️",
    "🅾️",
    "🆎",
    "⭐",
    "🌟",
    "💫",
    "✨",
    "🎯",
    "🎨",
    "🎵",
    "🎮",
    "💎",
    "🔥",
    "❤️",
    "💜",
    "💙",
    "💚",
    "💛",
    "🧡",
    "🌸",
    "🌺",
    "🍀",
    "🌈",
    "⚡",
    "🎪",
    "🎭",
    "🎬",
    "🐱",
    "🐶",
    "🦊",
    "🐻",
    "🐼",
    "🐯",
    "🦁",
    "🐸",
    "🍎",
    "🍊",
    "🍋",
    "🍇",
    "🍓",
    "🍑",
    "🍒",
    "🍌",
    "☀️",
    "🌙",
    "⛅",
    "❄️",
    "🌊",
    "🍂",
    "🌻",
    "🌹",
    "⚽",
    "🏀",
    "🎾",
    "🎳",
    "♠️",
    "♥️",
    "♦️",
    "♣️",
    "🎂",
    "🎁",
    "🎈",
    "🎀",
    "👑",
    "🏆",
    "🔔",
    "💡",
    "🚀",
    "✈️",
    "🚗",
    "🏠",
    "📱",
    "💻",
    "📚",
    "✏️",
    "😀",
    "😎",
    "🤩",
    "🥳",
    "😺",
    "👻",
    "🤖",
    "👽",
] as const;

export const DEFAULT_ITEM_EMOJI = "⭐";

/** 一時期保存された Lucide 風 ID を、表示・編集用の絵文字に寄せる */
const LUCIDE_STYLE_ID_TO_EMOJI: Record<string, string> = {
    star: "⭐",
    sparkles: "✨",
    target: "🎯",
    trophy: "🏆",
    flame: "🔥",
    heart: "❤️",
    music: "🎵",
    "gamepad-2": "🎮",
    gem: "💎",
    zap: "⚡",
    palette: "🎨",
    "circle-dot": "🔘",
    "flower-2": "🌸",
    sun: "☀️",
    moon: "🌙",
    cloud: "⛅",
    snowflake: "❄️",
    droplets: "🌊",
    leaf: "🍂",
    apple: "🍎",
    cat: "🐱",
    dog: "🐶",
    fish: "🐠",
    bird: "🐦",
    car: "🚗",
    home: "🏠",
    smartphone: "📱",
    laptop: "💻",
    "book-open": "📚",
    "pen-line": "✏️",
    rocket: "🚀",
    plane: "✈️",
    gift: "🎁",
    cake: "🎂",
    crown: "👑",
    bell: "🔔",
    "bar-chart-3": "📊",
    "map-pin": "🗾",
    "minus-circle": "➖",
    circle: "⚪",
};

export function coerceStoredEmojiToDisplay(raw: string | undefined | null): string {
    const s = (raw ?? "").trim();
    if (!s) return DEFAULT_ITEM_EMOJI;
    const mapped = LUCIDE_STYLE_ID_TO_EMOJI[s];
    if (mapped) return mapped;
    return s;
}

/** デフォルトアクセント色（Counter / Flowchart 等で共通） */
export const DEFAULT_ACCENT_COLOR = "#a855f7";

export const COLOR_OPTIONS = [
    { value: "#ef4444", label: "レッド" },
    { value: "#f97316", label: "オレンジ" },
    { value: "#eab308", label: "イエロー" },
    { value: "#22c55e", label: "グリーン" },
    { value: "#06b6d4", label: "シアン" },
    { value: "#3b82f6", label: "ブルー" },
    { value: "#8b5cf6", label: "バイオレット" },
    { value: "#a855f7", label: "パープル" },
    { value: "#ec4899", label: "ピンク" },
    { value: "#dc2626", label: "ダークレッド" },
    { value: "#94a3b8", label: "グレー" },
    { value: "#6b7280", label: "ダークグレー" },
];
